kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
  namespace: default
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}